[build]
  # Diretório de publicação (onde o Angular gera os arquivos estáticos)
  publish = "dist/grace-book-front/browser"
  
  # Comando de build
  command = "npm run build:prod"

[build.environment]
  # Versão do Node.js (compatível com Angular 20)
  NODE_VERSION = "20"
  # Configuração para resolver conflitos de dependências
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Desabilitar scanner de secrets (configurações Firebase são públicas)
  SECRETS_SCAN_ENABLED = "false"
  
  # Variáveis de ambiente para produção
  # Firebase Configuration - CONFIGURAR NO NETLIFY DASHBOARD
  NG_APP_FIREBASE_API_KEY = ""
  NG_APP_FIREBASE_AUTH_DOMAIN = ""
  NG_APP_FIREBASE_PROJECT_ID = ""
  NG_APP_FIREBASE_STORAGE_BUCKET = ""
  NG_APP_FIREBASE_MESSAGING_SENDER_ID = ""
  NG_APP_FIREBASE_APP_ID = ""
  NG_APP_FIREBASE_MEASUREMENT_ID = ""
  
  # API Configuration - CONFIGURAR NO NETLIFY DASHBOARD
  NG_APP_API_URL = "https://grace-book-back.onrender.com"
  
  # ASAAS Configuration - CONFIGURAR NO NETLIFY DASHBOARD
  NG_APP_ASAAS_API_KEY = ""
  NG_APP_ASAAS_ENVIRONMENT = "production"
  NG_APP_ASAAS_BASE_URL = ""
  NG_APP_ASAAS_WEBHOOK_URL = ""
  
  # Payment Configuration - CONFIGURAR NO NETLIFY DASHBOARD
  NG_APP_PAYMENT_SUCCESS_URL = "https://sedecampestre.oceanodagraca.com/payment-success"
  NG_APP_PAYMENT_CANCEL_URL = "https://sedecampestre.oceanodagraca.com/booking"
  NG_APP_PAYMENT_WEBHOOK_SECRET = ""

# Configurações de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: https:; connect-src 'self' https://api-sandbox.asaas.com https://api.asaas.com https://*.firebaseapp.com https://*.googleapis.com https://grace-book-back.onrender.com;"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos de build
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"