[build]
  # Diretório de publicação (onde o Angular gera os arquivos estáticos)
  publish = "dist/grace-book-front/browser"
  
  # Comando de build
  command = "npm run build:prod"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"
  # Configuração para resolver conflitos de dependências
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Variáveis de ambiente (substitua pelos seus valores reais)
  # NG_APP_API_URL = "https://seu-backend.com/api"
  # NG_APP_FIREBASE_API_KEY = "sua-chave-firebase"
  # NG_APP_FIREBASE_AUTH_DOMAIN = "seu-projeto.firebaseapp.com"
  # NG_APP_FIREBASE_PROJECT_ID = "seu-projeto-id"
  # NG_APP_FIREBASE_STORAGE_BUCKET = "seu-projeto.firebasestorage.app"
  # NG_APP_FIREBASE_MESSAGING_SENDER_ID = "seu-sender-id"
  # NG_APP_FIREBASE_APP_ID = "seu-app-id"
  # NG_APP_FIREBASE_MEASUREMENT_ID = "seu-measurement-id"

# Configurações de redirecionamento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api-sandbox.asaas.com https://api.asaas.com https://*.firebaseapp.com https://*.googleapis.com;"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos de build
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
