[build]
  # Diretório de publicação (onde o Angular gera os arquivos estáticos)
  publish = "dist/grace-book-front/browser"
  
  # Comando de build
  command = "npm run build:prod"

[build.environment]
  # Versão do Node.js (compatível com Angular 20)
  NODE_VERSION = "20"
  # Configuração para resolver conflitos de dependências
  NPM_FLAGS = "--legacy-peer-deps"

# Configurações de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api-sandbox.asaas.com https://api.asaas.com https://*.firebaseapp.com https://*.googleapis.com;"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos de build
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"